# docker-compose.yml
version: '3'

services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./docker-data/ollama:/root/.ollama
    networks:
      - xai-network
    ports:
      - 11434:11434

  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: xai-serving:latest
    networks:
      - xai-network
    ports:
      - 8080:8080

  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: xai-streamlit:latest
    networks:
      - xai-network
    ports:
      - 8601:8601

networks:
  xai-network:


